// ---------------------------------------------------------------------------
// Preload — the ONLY surface the renderer sees. A minimal, typed IPC bridge
// exposed via contextBridge. The renderer never gets ipcRenderer or any Node
// primitive directly.
// ---------------------------------------------------------------------------

import { contextBridge, ipcRenderer } from 'electron'
import type {
  AppSettings,
  SecretsInput,
  SecretsPresence,
  TunnelStatus,
  AgentStreamMessage,
  SendResult,
  ClaudeAuthStatus,
  Conversation,
  StoredMessage,
  AttachmentRef,
  ModelOption,
  SlashCommandInfo,
  PermissionRequest,
  Project,
  FsEntry,
  FilePreview,
  ShellRunResult,
  GitStatus,
  ChangedFile,
  FileDiff,
  CommitResult,
  CommitInfo,
  GitPushResult,
  GhPrResult,
  PresenceActivity,
} from '../shared/types'

const api = {
  settings: {
    get: (): Promise<AppSettings> => ipcRenderer.invoke('settings:get'),
    set: (s: AppSettings): Promise<AppSettings> => ipcRenderer.invoke('settings:set', s),
  },
  secrets: {
    presence: (): Promise<SecretsPresence> => ipcRenderer.invoke('secrets:presence'),
    set: (input: SecretsInput): Promise<SecretsPresence> =>
      ipcRenderer.invoke('secrets:set', input),
    importKey: (path: string): Promise<SecretsPresence> =>
      ipcRenderer.invoke('secrets:importKey', path),
  },
  dialog: {
    pickKey: (): Promise<string | null> => ipcRenderer.invoke('dialog:pickKey'),
    pickAttachments: (): Promise<AttachmentRef[]> =>
      ipcRenderer.invoke('dialog:pickAttachments'),
  },
  project: {
    list: (): Promise<Project[]> => ipcRenderer.invoke('project:list'),
    add: (): Promise<Project | null> => ipcRenderer.invoke('project:add'),
    delete: (id: string): Promise<boolean> => ipcRenderer.invoke('project:delete', id),
    conversations: (projectId: string): Promise<Conversation[]> =>
      ipcRenderer.invoke('project:conversations', projectId),
  },
  fs: {
    listDir: (projectId: string, relPath: string): Promise<FsEntry[]> =>
      ipcRenderer.invoke('fs:listDir', projectId, relPath),
    readFile: (projectId: string, relPath: string): Promise<FilePreview> =>
      ipcRenderer.invoke('fs:readFile', projectId, relPath),
    stat: (projectId: string, relPath: string): Promise<{ type: 'dir' | 'file'; size: number }> =>
      ipcRenderer.invoke('fs:stat', projectId, relPath),
  },
  conv: {
    list: (agentId: string): Promise<Conversation[]> => ipcRenderer.invoke('conv:list', agentId),
    create: (
      agentId: string,
      title: string,
      projectId?: string | null,
    ): Promise<Conversation> => ipcRenderer.invoke('conv:create', agentId, title, projectId),
    rename: (id: string, title: string): Promise<Conversation> =>
      ipcRenderer.invoke('conv:rename', id, title),
    delete: (id: string): Promise<boolean> => ipcRenderer.invoke('conv:delete', id),
    messages: (conversationId: string): Promise<StoredMessage[]> =>
      ipcRenderer.invoke('conv:messages', conversationId),
    setModelEffort: (id: string, model: string, effort: string, contextWindow: string): Promise<Conversation> =>
      ipcRenderer.invoke('conv:setModelEffort', id, model, effort, contextWindow),
  },
  tunnel: {
    status: (): Promise<TunnelStatus> => ipcRenderer.invoke('tunnel:status'),
    restart: (): Promise<TunnelStatus> => ipcRenderer.invoke('tunnel:restart'),
    onStatus: (cb: (s: TunnelStatus) => void): (() => void) => {
      const handler = (_e: unknown, s: TunnelStatus) => cb(s)
      ipcRenderer.on('tunnel:status', handler)
      return () => ipcRenderer.removeListener('tunnel:status', handler)
    },
  },
  agent: {
    // streamId is generated by the renderer so it can register its
    // streamId -> message mapping BEFORE any event is delivered (no race).
    send: (
      agentId: string,
      text: string,
      conversationId: string,
      streamId: string,
      attachments?: AttachmentRef[],
      permissionMode?: 'default' | 'bypassPermissions',
    ): Promise<SendResult> =>
      ipcRenderer.invoke('agent:send', {
        agentId,
        text,
        conversationId,
        streamId,
        attachments,
        permissionMode,
      }),
    cancel: (streamId: string): Promise<boolean> =>
      ipcRenderer.invoke('agent:cancel', streamId),
    onEvent: (cb: (msg: AgentStreamMessage) => void): (() => void) => {
      const handler = (_e: unknown, msg: AgentStreamMessage) => cb(msg)
      ipcRenderer.on('agent:event', handler)
      return () => ipcRenderer.removeListener('agent:event', handler)
    },
    onPermissionRequest: (cb: (req: PermissionRequest) => void): (() => void) => {
      const handler = (_e: unknown, req: PermissionRequest) => cb(req)
      ipcRenderer.on('agent:permission', handler)
      return () => ipcRenderer.removeListener('agent:permission', handler)
    },
    respondPermission: (requestId: string, approved: boolean): void =>
      ipcRenderer.send('agent:permission:respond', { requestId, approved }),
  },
  claude: {
    authStatus: (): Promise<ClaudeAuthStatus> => ipcRenderer.invoke('claude:authStatus'),
    models: (): Promise<ModelOption[]> => ipcRenderer.invoke('claude:models'),
    commands: (): Promise<SlashCommandInfo[]> => ipcRenderer.invoke('claude:commands'),
  },
  presence: {
    updateActivity: (activity: PresenceActivity): Promise<boolean> =>
      ipcRenderer.invoke('presence:updateActivity', activity),
  },
  shell: {
    openExternal: (url: string): Promise<void> => ipcRenderer.invoke('shell:openExternal', url),
    run: (projectId: string, command: string): Promise<ShellRunResult> =>
      ipcRenderer.invoke('shell:run', projectId, command),
  },
  git: {
    status: (projectId: string): Promise<GitStatus> => ipcRenderer.invoke('git:status', projectId),
    changedFiles: (projectId: string): Promise<ChangedFile[]> =>
      ipcRenderer.invoke('git:changedFiles', projectId),
    fileDiff: (projectId: string, relPath: string): Promise<FileDiff> =>
      ipcRenderer.invoke('git:fileDiff', projectId, relPath),
    commit: (projectId: string, relPaths: string[], message: string): Promise<CommitResult> =>
      ipcRenderer.invoke('git:commit', projectId, relPaths, message),
    push: (projectId: string): Promise<GitPushResult> =>
      ipcRenderer.invoke('git:push', projectId),
    commitsSinceUpstream: (projectId: string): Promise<CommitInfo[]> =>
      ipcRenderer.invoke('git:commitsSinceUpstream', projectId),
    ghPrCreate: (projectId: string, title: string, body: string): Promise<GhPrResult> =>
      ipcRenderer.invoke('git:ghPrCreate', projectId, title, body),
  },
}

contextBridge.exposeInMainWorld('api', api)

export type GlCodeApi = typeof api
